name: 'user-web'
port: 8021

user_srv:
  host: '192.1680.100'
  port: 50051
  name: 'user_srv'

jwt:
  key: 'v!YhrZjQmHmqRsk$k#6&aK4zcGz^wwdZ'

sms:
  key: 'LTAI5t8MbaSmhXqVMyPmVDnT'
  secret: 'UugwgeGAXPeBlYYRNobOF05nf5TevZ'
  sign_name: '阿里云短信测试'
  template_code: 'SMS_154950909'
  phone_numbers: '18070155633'

redis:
  host: '192.168.0.107'
  port: 6379
  expire: 5

consul:
  host: '192.168.0.107'
  port: 8500